version: '3.7'
services:
  app-server:
    container_name: app-server
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    build:
      context: ./
    image: app-server
    ports:
      - '3000:3000'
